config/routes.rb
Rails.application.routes.draw do
  # root "articles#index"
  root "home#index"

  get 'signup/', to:'signup#index'
  post 'signup/', to:'signup#create'

  get 'login/', to:'session#index'
  post 'login/', to:'session#create'
  delete 'logout/', to:'session#destroy'

  get 'password/', to:'password#index'
  patch 'password/', to:'password#update'

  get 'users/', to:'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user 
end 

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    validates :email, presence: true, format: { with:/.*/, message:"invalid email address" }
    validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id:  session[:user_id])
        end
    end

    def logged_in
        if Current.user.nil? 
            redirect_to login_path, alert: 'You must be logged in !'
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController

    before_action :logged_in

    def index 
    end

    def update 
        if Current.user.update(password_params)
            redirect_to root_path, notice: 'Password updated successfully'
        else 
            render :index
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def index 
    end

    def create 
        user = User.find_by(email: params[:email])
        
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice:'Logged in with success!'
      
       else
           flash[:alert] = 'Invalid credentials'
           render :index
       end
    end 

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'logged out!!'
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index

    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice:"Created Account"
    else 
      # flash[:alert] = "some error occured, try again"
      render :index
    end
  end

  private

  def user_params

    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # users = User.all()
    # puts users.inspect.length
    # render plain: users.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br/>
<h1>Home Page</h1>

<% if Current.user %>
<h3>Welcome back <%= Current.user.name %> </h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render partial:"partials/navbar" %>

    <div class="container">
      <%= render partial:"partials/flash" %>
      <%= yield %>
    </div>

  </body>
  
</html>

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <%= link_to "Home", root_path, class:"navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <%= link_to "All users", users_path, class:"nav-link" %>
            </div>

            <div class="navbar-nav ms-auto mb-2 mb-lg-0">

                <% if Current.user %>
                    <%= link_to Current.user.name, password_path,class:"nav-link" %> 
                    <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-dark" %> 
                <% else %>
                    <%= link_to "Login", login_path, class:"nav-link" %>
                    <%= link_to "Sign Up", signup_path, class:"nav-link" %>
                <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/password/index.html.erb
<br/><br/>
<h1> Edit Password </h1>
<br/>

<%= form_with model: Current.user, url: password_path, data: { turbo: false } do |form| %>

    <%if form.object.errors.any? %>

        <div class="alert alert-danger" role="alert">
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>

    <% end %>

    <div class="mb-3">
        <%=form.text_field :password, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="mb-3">
        <%=form.text_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
    </div>

    <div class="mb-3">
        <%=form.submit "Update Password",method: :patch, class: "btn btn-primary"%>
    </div>

<% end %>

app/views/session/index.html.erb
<br/><br/>
<h1> Login Page </h1>
<br/>

<%= form_with url: login_path, data: { turbo: false } do |form| %>

    <div class="mb-3">
        <%=form.email_field :email, class: "form-control", placeholder: "Email" %>
    </div>

    <div class="mb-3">
        <%=form.text_field :password, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="mb-3">
        <%=form.submit "Log In", class: "btn btn-primary"%>
    </div>

<% end %>

app/views/signup/index.html.erb
<br/><br/>
<h1>SignUp Page</h1>
<br/>

<%= form_with model: @user, url: signup_path, data: { turbo: false } do |form| %>

    <%if form.object.errors.any? %>

        <div class="alert alert-danger" role="alert">
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>

    <% end %>

    <div class="mb-3">
        <%=form.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>

    <div class="mb-3">
        <%=form.email_field :email, class: "form-control", placeholder: "Email" %>
    </div>

    <div class="mb-3">
        <%=form.text_field :password, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="mb-3">
        <%=form.text_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
    </div>

    <div class="mb-3">
        <%=form.submit "Sign Up", class: "btn btn-primary"%>
    </div>

<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<table class="table">
    <thead>
        <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        </tr>
    </thead>
    <tbody>

        <% User.all.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
            </tr>
        <% end %>
    </tbody>
</table>